package lexer;
 
/**
 *  This file is automatically generated<br>
 *  - it contains the enumberation of all of the tokens
*/
public enum Tokens {
  BogusToken,Program,Int,BOOLean,If,
    Then,Else,While,Function,Return,
    Identifier,INTeger,LeftBrace,RightBrace,LeftParen,
    RightParen,LeftBracket,RightBracket,Comma,Assign,
    Equal,NotEqual,Greater,GreaterEqual,Less,
    LessEqual,Plus,Minus,Or,And,
    Multiply,Divide,Comment,Hash,Begin,
    End,In,Utf16String,Utf16StringLit,TimestampType,
    TimestampLit
}
